name: HalfminerREST
version: ${project.version}
description: Halfminer.de HTTP API
author: Kakifrucht
website: https://halfminer.de
api-version: '1.14'

main: de.halfminer.hmr.HalfminerREST
depend: [HalfminerSystem]

commands:
  hmr:
    description: Base command
    aliases: [hmrapi]
    permission: hmr.command

permissions:
  hmr.*:
    description: Access to all permissions
    default: op
    children:
      hmr.command: true
  hmr.command:
    description: Access to hmr command
