name: HalfminerSystem
version: 3.0
description: Halfminer.de Coreplugin
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hms.HalfminerSystem

commands:
  ?:
    description: Bukkit override, protects from viewing all commands
  hms:
    description: HalfminerSystem basecommand
  hmstore:
    description: Data storage manipulation
  signedit:
    description: Edit the contents of a sign or copy it
    aliases: [se]
  lag:
    description: View the connection info
    aliases: [ping]
  stats:
    description: View the statistics of a player
  neutp:
    description: Teleports the player to a random location
  home:
    description: Teleports the player to his home
  vtapi:
    description: Command API
    aliases: [c,hilfe,spenden,regeln,neutp,vote,rang,tools,kiste,deo]
permissions:
  hms.*:
    description: Access to all permissions
    default: op
    hms.default: true
    hms.lag: true
    hms.lag.others: true
    hms.stats: true
    hms.neutp: true
    hms.home: true
    hms.signedit: true
    hms.admin: true
    hms.notifylag: true
    hms.bypass.*: true
  hms.bypass.*:
    description: Access to all bypass permission
    default: op
    hms.bypass.combatlog: true
    hms.bypass.capsfilter: true
    hms.bypass.commandfilter: true
    hms.bypass.hopperlimit: true
    hms.bypass.bedrockcheck: true
    hms.bypass.nokillfarming: true
    hms.bypass.skilllevel: true
    hms.bypass.statsrightclick: true
  hms.default:
    default: true
    description: Default permission
  hms.stats:
    default: true
    description: Access to stats command
  hms.neutp:
    default: true
    description: Access to neutp command
  hms.home:
    default: true
    description: Access to home command
  hms.lag:
    description: Access to lag command
  hms.lag.others:
    description: View the latency of other players
  hms.signedit:
    description: Access to sign editing
  hms.admin:
    description: Access to administrative commands
  hms.notifylag:
    description: Sends lag notifications to admin
  hms.bypass.combatlog:
    description: Bypass combat logging
  hms.bypass.capsfilter:
    description: Bypass chat caps filter
  hms.bypass.commandfilter:
    description: Bypass chat command filter
  hms.bypass.hopperlimit:
    description: Bypass hopper placement limit
  hms.bypass.bedrockcheck:
    description: Bypass bedrock movement check
  hms.bypass.nokillfarming:
    description: Bypass killfarming check
  hms.bypass.skilllevel:
    description: Bypass setting of skilllevel
  hms.bypass.statsrightclick:
    description: Bypass stats on rightclick