name: HalfminerSystem
version: 2.4
description: Halfminer.de Coreplugin
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hms.HalfminerSystem

commands:
  ?:
    description: Bukkit override, protects from viewing all commands
  hms:
    description: HalfminerSystem basecommand
  signedit:
    description: Edit the contents of a sign or copy it
    aliases: [se]
  lag:
    description: View the connection info
    aliases: [ping]
  vtapi:
    description: Command API
    aliases: [c,hilfe,spenden,stats,regeln,neutp,vote,rang,tools,kiste,deo]
permissions:
  hms.*:
    description: Access to all permissions
    default: op
    hms.default: true
    hms.lag: true
    hms.lag.others: true
    hms.signedit: true
    hms.admin: true
    hms.notifylag: true
    hms.bypass.*: true
  hms.bypass.*:
    description: Access to all bypass permission
    default: op
    hms.bypass.combatlog: true
    hms.bypass.capsfilter: true
    hms.bypass.commandfilter: true
    hms.bypass.hopperlimit: true
    hms.bypass.bedrockcheck: true
    hms.bypass.nokillfarming: true
  hms.default:
    default: true
    description: Default permission
  hms.lag:
    description: Access to lag command
  hms.lag.others:
    description: View the latency of other players
  hms.signedit:
    description: Access to sign editing
  hms.admin:
    description: Access to administrative commands
  hms.notifylag:
    description: Sends lag notifications to admin
  hms.bypass.combatlog:
    description: Bypass combat logging
    default: op
  hms.bypass.capsfilter:
    description: Bypass chat caps filter
    default: op
  hms.bypass.commandfilter:
    description: Bypass chat command filter
    default: op
  hms.bypass.hopperlimit:
    description: Bypass hopper placement limit
    default: op
  hms.bypass.bedrockcheck:
    description: Bypass bedrock movement check
    default: op
  hms.bypass.nokillfarming:
    description: Bypass killfarming check
    default: op