name: HalfminerSystem
version: 3.22.7
description: Halfminer.de Coreplugin
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hms.HalfminerSystem
depend: [Essentials]
softdepend: [Vault]

commands:
  ?:
    description: Bukkit override, protects from viewing all commands
    aliases: [alias]
  chat:
    description: Chat manipulation tools
    aliases: [c]
  customtext:
    description: Show parsed customtext
    aliases: [hmstext]
  disposal:
    description: Open portable disposal
    aliases: [bin]
  hms:
    description: HalfminerSystem base command
    aliases: [halfminer, halfminersystem, hsystem, hmsystem]
  hmsapi:
    description: Command script API
  hmstore:
    description: Data storage manipulation
  home:
    description: Teleports the player to his home
    aliases: [h]
  lag:
    description: View the connection info
    aliases: [ping]
  newtp:
    description: Teleports the player to a random location
    aliases: [tpnew, neutp, tpneu]
  repair:
    description: Repair the currently held item
    aliases: [fix]
  sell:
    description: Earn money by selling farm supplies
    aliases: [verkauf, vk]
  signedit:
    description: Edit the contents of a sign or copy it
    aliases: [se]
  spawn:
    description: Teleport to the spawn
    aliases: [sa]
  stats:
    description: View the statistics of a player
    aliases: [st]
  vote:
    description: Vote for the server
permissions:
  hms.*:
    description: Access to all permissions
    default: op
    children:
      hms.antixray.notify: true
      hms.admin: true
      hms.chat: true
      hms.chat.advanced: true
      hms.customttext: true
      hms.default: true
      hms.disposal: true
      hms.home: true
      hms.lag: true
      hms.lag.others: true
      hms.lag.notify: true
      hms.moderator: true
      hms.newtp: true
      hms.sell: true
      hms.sell.auto: true
      hms.signedit: true
      hms.spawn: true
      hms.spawn.others: true
      hms.spawn.set: true
      hms.stats: true
      hms.vote: true
      hms.bypass.*: true
      hms.chat.*: true
      hms.level.*: true
      hms.repair.*: true
  hms.bypass.*:
    description: Access to all bypass permission
    default: op
    children:
      hms.bypass.antixray: true
      hms.bypass.combatlog: true
      hms.bypass.commandfilter: true
      hms.bypass.glitchcheck: true
      hms.bypass.hopperlimit: true
      hms.bypass.nethercheck: true
      hms.bypass.nokillfarming: true
      hms.bypass.pvp: true
      hms.bypass.skilllevel: true
      hms.bypass.statsrightclick: true
      hms.bypass.tabcomplete: true
      hms.bypass.teleportchecks: true
      hms.bypass.teleporttimer: true
  hms.chat.*:
    description: Access to all chat manager related permissions (not the command)
    default: op
    children:
      hms.chat.allowcaps: true
      hms.chat.allowcolor: true
      hms.chat.allowformatcode: true
      hms.chat.allowlinks: true
      hms.chat.bypassglobalmute: true
      hms.chat.spam: true
      hms.chat.topformat: true
  hms.level.*:
    description: Access to all commands restricted by level
    default: op
    children:
      hms.level.0: true
      hms.level.1: true
      hms.level.2: true
      hms.level.3: true
      hms.level.4: true
      hms.level.5: true
      hms.level.6: true
  hms.repair.*:
    description: Full access to repair command
    default: op
    children:
      hms.repair: true
      hms.repair.all: true
      hms.repair.nocooldown: true
      hms.repair.stacks: true
  hms.default:
    default: true
    description: Default permission
  hms.home:
    default: true
    description: Access to home command
  hms.level.0:
    default: true
    description: Access to features restricted to level 0
  hms.newtp:
    default: true
    description: Access to newtp command
  hms.stats:
    default: true
    description: Access to stats command
  hms.sell:
    default: true
    description: Access to sell command
  hms.vote:
    default: true
    description: Access to vote command
  hms.admin:
    description: Access to administrative commands
  hms.antixray.notify:
    description: Get notified on join if a player moved past the AntiXRay treshold
  hms.bypass.antixray:
    description: Bypass antixray functionality
  hms.bypass.combatlog:
    description: Bypass combat logging
  hms.bypass.commandfilter:
    description: Bypass chat command filter
  hms.bypass.glitchcheck:
    description: Bypass glitch movement check
  hms.bypass.hopperlimit:
    description: Bypass hopper placement limit
  hms.bypass.nethercheck:
    description: Bypass netherroof position check
  hms.bypass.nokillfarming:
    description: Bypass killfarming check
  hms.bypass.pvp:
    description: Bypass pvp modifications
  hms.bypass.skilllevel:
    description: Bypass setting of skilllevel
  hms.bypass.statsrightclick:
    description: Bypass stats on rightclick
  hms.bypass.tabcomplete:
    description: Bypass tabcomplete
  hms.bypass.teleportcheck:
    description: Bypass glitch protection teleport check
  hms.bypass.teleporttimer:
    description: Bypass teleport timer
  hms.chat:
    description: Access to chat clearing command
  hms.chat.advanced:
    description: Access to advanced chat manipulation
  hms.chat.allowcaps:
    description: Stops filtering capitalised messages
  hms.chat.allowcolor:
    description: Access to color codes in chat
  hms.chat.allowformatcode:
    description: Access to format codes in chat
  hms.chat.allowlinks:
    description: Allows posting links
  hms.chat.spam:
    description: Bypass spam check protection
  hms.chat.topformat:
    description: Gives user format with highest priority
  hms.customttext:
    description: Access to customtext command
  hms.disposal:
    description: Access to disposal command
  hms.lag:
    description: Access to lag command
  hms.lag.others:
    description: View the latency of other players
  hms.lag.notify:
    description: Sends lag notifications to admin
  hms.level.1:
    description: Access to commands restricted to level 1
  hms.level.2:
    description: Access to commands restricted to level 2
  hms.level.3:
    description: Access to commands restricted to level 3
  hms.level.4:
    description: Access to commands restricted to level 4
  hms.level.5:
    description: Access to commands restricted to level 5
  hms.level.6:
    description: Access to commands restricted to level 6
  hms.moderator:
    description: Access to moderative commands
  hms.repair:
    description: Access to repair command
  hms.repair.all:
    description: Access to repair all command
  hms.repair.nocooldown:
    description: No repair cooldown
  hms.repair.stacks:
    description: Allows single stacks to be repaired
  hms.sell.auto:
    description: Access to automatic selling
  hms.signedit:
    description: Access to sign editing
  hms.spawn:
    default: true
    description: Access to spawn command
  hms.spawn.others:
    description: Teleport other players to spawn
  hms.spawn.set:
    description: Access to spawn set command
