name: HalfminerSystem
version: 3.5.9
description: Halfminer.de Coreplugin
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hms.HalfminerSystem
depend: [Essentials]

commands:
  ?:
    description: Bukkit override, protects from viewing all commands
  hms:
    description: HalfminerSystem Base command
  hmstore:
    description: Data storage manipulation
  chat:
    description: Chat manipulation tools
    aliases: [c]
  signedit:
    description: Edit the contents of a sign or copy it
    aliases: [se]
  lag:
    description: View the connection info
    aliases: [ping]
  stats:
    description: View the statistics of a player
  neutp:
    description: Teleports the player to a random location
  home:
    description: Teleports the player to his home
  verkauf:
    description: Earn money buy selling farm supplies
    aliases: [vk]
  vote:
    description: Vote for the server
  vtapi:
    description: VT Command API
    aliases: [hilfe, spenden, regeln, rang, tools, kiste, deo, forum]
permissions:
  hms.*:
    description: Access to all permissions
    default: op
    hms.default: true
    hms.lag: true
    hms.lag.others: true
    hms.lag.notify: true
    hms.moderator: true
    hms.stats: true
    hms.chat: true
    hms.chat.advanced: true
    hms.neutp: true
    hms.home: true
    hms.verkauf: true
    hms.vote: true
    hms.signedit: true
    hms.admin: true
    hms.bypass.*: true
    hms.level.*: true
  hms.bypass.*:
    description: Access to all bypass permission
    default: op
    hms.bypass.combatlog: true
    hms.bypass.capsfilter: true
    hms.bypass.globalmute: true
    hms.bypass.commandfilter: true
    hms.bypass.hopperlimit: true
    hms.bypass.bedrockcheck: true
    hms.bypass.nethercheck: true
    hms.bypass.nokillfarming: true
    hms.bypass.skilllevel: true
    hms.bypass.statsrightclick: true
    hms.bypass.merchant: true
    hms.bypass.pvp: true
  hms.level.*:
    description: Access to all commands restricted by level
    default: op
    hms.level.0: true
    hms.level.1: true
    hms.level.2: true
    hms.level.3: true
    hms.level.4: true
    hms.level.5: true
    hms.level.6: true
  hms.default:
    default: true
    description: Default permission
  hms.stats:
    default: true
    description: Access to stats command
  hms.neutp:
    default: true
    description: Access to neutp command
  hms.home:
    default: true
    description: Access to home command
  hms.verkauf:
    default: true
    description: Access to verkauf command
  hms.vote:
    default: true
    description: Access to vote command
  hms.chat:
    description: Access to chat clearing command
  hms.chat.advanced:
    description: Access to advanced chat manipulation
  hms.lag:
    description: Access to lag command
  hms.lag.others:
    description: View the latency of other players
  hms.lag.notify:
      description: Sends lag notifications to admin
  hms.signedit:
    description: Access to sign editing
  hms.admin:
    description: Access to administrative commands
  hms.moderator:
    description: Access to moderative commands
  hms.bypass.combatlog:
    description: Bypass combat logging
  hms.bypass.capsfilter:
    description: Bypass chat caps filter
  hms.bypass.globalmute:
    description: Bypass globalmute
  hms.bypass.commandfilter:
    description: Bypass chat command filter
  hms.bypass.hopperlimit:
    description: Bypass hopper placement limit
  hms.bypass.bedrockcheck:
    description: Bypass bedrock movement check
  hms.bypass.nethercheck:
    description: Bypass netherroof position check
  hms.bypass.nokillfarming:
    description: Bypass killfarming check
  hms.bypass.skilllevel:
    description: Bypass setting of skilllevel
  hms.bypass.statsrightclick:
    description: Bypass stats on rightclick
  hms.bypass.merchant:
    description: Bypass merchant restrictions
  hms.bypass.pvp:
    description: Bypass PvP changes
  hms.level.0:
    default: true
    description: Access to commands restricted to level 0
  hms.level.1:
    description: Access to commands restricted to level 1
  hms.level.2:
    description: Access to commands restricted to level 2
  hms.level.3:
    description: Access to commands restricted to level 3
  hms.level.4:
    description: Access to commands restricted to level 4
  hms.level.5:
    description: Access to commands restricted to level 5
  hms.level.6:
    description: Access to commands restricted to level 6