#HalfminerBattle Config
battleMode:
  global:
    #Disable hunger loss in all arenas
    noHungerLoss: true
    #These commands are not blocked while in battle, set commands shouldn't interfere with players state
    nonBlockedCommands:
    - ban
    - rules
    - msg
    - m
    - r
    #Time in seconds the queue cooldown will prevent a player to join a game again
    queueCooldownTimeSeconds: 15
    #Save players inventories to disk before battle, to ensure absolutely no data loss
    saveInventoryToDisk: true
    #Amount of hours after stored inventories should be deleted (async worker called in 1 hour intervals)
    #saveInventoryToDisk must be true, 0 to disable
    saveInventoryToDiskCleanupAfterHours: 24
    #Distance in blocks from all spawn points in all arenas that must be met to allow the teleport
    teleportSpawnDistance: 10
  duel:
    #Broadcast duel wins
    broadcastWin: true
    #Maximum duel time in seconds
    gameTime: 300
    #Time in seconds until server will broadcast that a dueling player is waiting to be dueled, 0 to disable
    waitingForMatchRemind: 30
  ffa:
    #Custom permission that can be added for bypasses of other plugins while in FFA, to prevent interferences (CombatLogger?)
    addPermissions:
    - 'hmb.example.bypass'
    #After how many deaths a player will be removed from the arena, set to 0 to disable
    removeAfterDeaths: 4
    #How many minutes player will be removed for at least when removeAfterDeaths causes removal from arena
    removeForMinutes: 3
    #Makes the players glow through walls while in FFA arena
    setGlowing: true
#Use '&' as color code
#Lines starting with '~' will be parsed to make commands clickable, close the command with another '/' (like /help/)
#Messages can be removed by simply setting the message to nothing ('')
localization:
  prefix: '&7Battle &e>>&r '
  adminArenaDoesntExist: '&7Die Arena &c%ARENA% &7existiert nicht'
  adminClearSpawns: '&7Der Spawn (oder alle Spawns) für die Arena &a%ARENA% &7wurde entfernt'
  adminCommandUsage: 'HalfminerBattle Version &6%VERSION% &r(System: &6%SYSTEMVERSION%&r)\n&6&lAdmin Kommandos:\n &f/hmb <modus>\n /hmb reload\n /hmb openinventory <dateiname> [-r]\n&6&lArena Kommandos:\n &f/hmb create <mode> <name>\n /hmb remove <mode> <arenaname>\n /hmb setspawn <mode> <arenaname> [spawnnumber]\n /hmb removespawn <mode> <arenaname> [spawnnumber]\n /hmb setkit <mode> <arenaname> [-e]\n /hmb forceend <mode> <arenaname>'
  adminCreate: '~&7Die Arena &a%ARENA% &7wurde erstellt. Verwende &e/hmb setspawn %MODE% %ARENA%/ &7um weitere Spawnpunkte setzen'
  adminCreateFailed: '&7Die Arena &c%ARENA% &7existiert bereits'
  adminForcedEnd: '&7Das Spiel in &a%MODE%-Arena %ARENA% &7wurde erfolgreich beendet'
  adminForcedEndError: '&c%MODE%-Arena %ARENA% &7existiert nicht oder ist nicht aktiv'
  adminNotDefined: '&7Der Modus &c%BATTLEMODE% &7hat keine administrativen Kommandos'
  adminRemove: '&7Die Arena &a%ARENA% &7wurde entfernt'
  adminSetEmptyKit: '&7Das leere Kit wurde für die Arena &a%ARENA% &7gesetzt'
  adminSetKit: '&7Das Kit für die Arena &a%ARENA% &7wurde gesetzt'
  adminSetSpawn: '&7Der Spawn für die Arena &a%ARENA% &7wurde gesetzt'
  adminSettingsReloaded: '&aDie Konfiguration wurde neugeladen'
  adminSettingsReloadedError: '&cFehler beim neu laden der Arena Konfiguration, siehe Konsole für weitere Informationen'
  adminUnknownBattleMode: '&cUnbekannter Spielmodus'
  adminOpenInventoryInvalid: '&cUngültige Datei'
  adminOpenInventoryRestored: '&7Das Inventar von &a%PLAYER% &7wurde wiederhergestellt'
  adminOpenInventoryRestoredError: '&c%PLAYER% &7ist aktuell im Spiel, das Inventar wurde nicht wiederhergestellt'
  adminOpenInventoryUnknownFile: '&cDatei nicht gefunden'
  modeDuelAddedToQueue: '~&7Du bist nun in der Warteschlange, verwende &a/duel leave/ &7zum verlassen'
  modeDuelChooseArena: '&7Klicke die Arena mit der Maus (&oChat öffnen zum anklicken&7), auf der du gegen &e%PLAYER% &7spielen willst: '
  modeDuelChooseArenaRandom: 'In einer &lzufälligen &rArena spielen\n(Gegner erhält Benachrichtigung)'
  modeDuelChooseArenaInvalid: '&cUngültige Auswahl, bitte versuche es erneut'
  modeDuelChooseArenaNoneAvailable: '&7Aktuell sind alle Arenen belegt, ihr werdet automatisch in die nächste freie Arena teleportiert'
  modeDuelChooseArenaRefreshed: '&7Die Auswahl wurde aktualisiert: '
  modeDuelCountdownStart: '&7Das Duell in der Arena &e%ARENA%&7 gegen &c%PLAYER%&7 startet in 5 Sekunden'
  modeDuelCountdownStartNokit: '&7Das Duell &lmit eigenen Sachen &7in der Arena &e%ARENA%&7 gegen &c%PLAYER%&7 startet in 5 Sekunden'
  modeDuelGameEndForced: '&cDas Duell wurde durch einen Administrator beendet und ist unentschieden'
  modeDuelGameEndForcedLog: 'Das Duell zwischen %PLAYERA% und %PLAYERB% in Arena %ARENA% wurde beendet'
  modeDuelGameLost: '&cDu hast das Duell gegen &e%PLAYER%&c verloren'
  modeDuelGameStarting: '&aDer Kampf beginnt!'
  modeDuelGameTime: '&7Das Duell gegen &e%PLAYER%&7 ist unentschieden'
  modeDuelGameWon: '&aDu hast das Duell gegen &e%PLAYER%&a gewonnen'
  modeDuelNotInQueue: '&cDu bist nicht in der Warteschlange'
  modeDuelOpponentChoseRandom: '&e%PLAYER% &7hat eine &lzufällige Arena &7ausgesucht'
  modeDuelPartnerChoosingArena: '&e%PLAYER%&7 wählt nun eine Arena aus, das Duell startet gleich'
  modeDuelPlayerWaitingForMatch: '~&e%PLAYER%&7 wartet auf einen Duellpartner. Gib &a/duel match/&7 für ein faires Duell mit gleicher Ausrüstung ein'
  modeDuelQueueRemovedNotTheCause: '&cDein Duellpartner hat die Warteschlange verlassen, womit du auch entfernt wurdest'
  modeDuelRequestAcceptError: '~&e%PLAYER% &7hat dir eine Anfrage zum Duell &cmit Arena Kit &7geschickt, verwende &a/duel %PLAYER%/ &7zum akzeptieren'
  modeDuelRequestAcceptErrorNokit: '~&e%PLAYER% &7hat dir eine Anfrage zum Duell &cmit eigenen Sachen &7geschickt, verwende &a/duel %PLAYER% nokit/ &7zum akzeptieren'
  modeDuelRequestAccepted: '&7Du hast die Herausforderung &aakzeptiert'
  modeDuelRequested: '~&e%PLAYER%&7 hat dir eine Duell Herausforderung geschickt. Gib &a/duel %PLAYER%/ &7ein, um sie zu akzeptieren'
  modeDuelRequestedNokit: '~&e%PLAYER%&7 hat dir eine Duell Herausforderung &lmit eigenen Sachen &7geschickt. Gib &a/duel %PLAYER% nokit/ &7ein, um sie zu akzeptieren'
  modeDuelRequestCancel: '&7Deine Herausforderung wurde zurückgezogen'
  modeDuelRequestCancelled: '&e%PLAYER% &7hat seine Herausforderung &czurückgezogen'
  modeDuelRequestExempt: '&7Du kannst &c%PLAYER% &7keine Anfragen schicken'
  modeDuelRequesteeNotAvailable: '&e%PLAYER%&c ist bereits in der Warteschlange oder im Spiel'
  modeDuelRequestSent: '~&7Deine Herausforderung wurde an &e%PLAYER% &7geschickt, verwende &a/duel leave/ &7zum zurückziehen'
  modeDuelRequestSentNokit: '~&7Deine Herausforderung &lohne Kit &7wurde an &e%PLAYER% &7geschickt, verwende &a/duel leave/ &7zum zurückziehen'
  modeDuelRequestWasAccepted: '&7Deine Anfrage wurde von &e%PLAYER% &aakzeptiert'
  modeDuelRequestWasWaitingForMatch: '&e%PLAYER% &7hat auf einen Partner gewartet, deine Anfrage wurde daher akzeptiert'
  modeDuelRequestYourself: '&cDu kannst dir selber keine Anfrage schicken'
  modeDuelShowHelp: '~&7Faire Duelle mit gleicher Ausrüstung in Arenen\n &e/&eduel <Spielername> - &7&oDuellanfrage schicken\n &e/&eduel <Spielername> nokit - &7&oDuellanfrage mit eigenen Sachen\n &a/duel match/ - &7&oDuellpartner finden\n &a/duel leave/ - &7&oWarteschlange verlassen\n &a/duel list/ - &7&oArenaliste anzeigen'
  modeDuelShowPartnerTitle: ' \n&fDuellpartner: &6&l%PLAYER%'
  modeDuelStartingLog: 'Duell startet zwischen %PLAYERA% und %PLAYERB% in Arena %ARENA%'
  modeDuelStartingLogNokit: 'Duell mit eigenen Sachen startet zwischen %PLAYERA% und %PLAYERB% in Arena %ARENA%'
  modeDuelTieLog: 'Das Duell in Arena %ARENA% zwischen %PLAYERA% und %PLAYERB% ist unentschieden ausgegangen'
  modeDuelTimeRunningOut: '&cDas Duell wird in 5 Sekunden abgebrochen'
  modeDuelTitleCountdown: 'Duell startet in...\n&e&l%TIME% &rSekunden'
  modeDuelTitleStart: ' \n&6&lStart!'
  modeDuelWinBroadcast: '&a%WINNER% &7hat gegen &c%LOSER% &7in der Arena &e%ARENA% &7gewonnen'
  modeDuelWinBroadcastNokit: '&a%WINNER% &7hat gegen &c%LOSER% &7in der Arena &e%ARENA% &7mit eigener Ausrüstung gewonnen'
  modeFFAArenaLeft: '&7Du hast die Arena &averlassen'
  modeFFACooldown: '&7Du kannst die Arena frühestens in &c%TIMELEFT% Sekunden &7betreten'
  modeFFADiedTooOften: '&cDu bist zu häufig am Stück gestorben und wurdest daher aus der Arena entfernt'
  modeFFAGameEndForced: '&7Das Spiel wurde durch einen Administrator beendet'
  modeFFAGameEndForcedLog: 'Folgende Spieler waren bei der Beendigung der Arena %ARENA% im Spiel: %PLAYERLIST%'
  modeFFAJoined: '~&e%ARENA% &7wurde betreten, verwende &a/ffa leave/ &7zum verlassen (ausloggen führt zum Tod)'
  modeFFAJoinTitle: ' \nZum verlassen: &a/ffa leave'
  modeFFAKillLog: '%KILLER% (%KILLSTREAK%er Killserie) hat %VICTIM% (%DEATHSTREAK%er Todesserie) in FFA Arena %ARENA% eliminiert'
  modeFFAList: '&7Alle FFA Arenen und deren aktuelle Belegung:'
  modeFFAListEmpty: '&cLeer'
  modeFFAListPlayers: '&7%ARENA% &e>> &r%PLAYERS%'
  modeFFALoggedOutLog: '%PLAYER% hat sich in FFA Arena %ARENA% ausgeloggt'
  modeFFANotInArena: '&cDu bist in keiner FFA Arena'
  modeFFAScoreboardHeader: '&6&lFFA Serien'
  modeFFASpawnProtectBar: 'Spawn PvP Schutz'
  modeFFASpawnProtected: '&e%PLAYER% &chat noch Spawn PvP Schutz'
  modeFFAUsage: '~&7Kämpfe in einer Arena gegen alle mit Kit und Killserien\n &a/ffa join/ [Arena] &7- Arena betreten\n &a/ffa leave/ &7- Arena verlassen\n &a/ffa list/ &7- Arenen und Spieler auflisten'
  modeFFAChooseArena: '&7Klicke die Arena mit der Maus (&oChat öffnen zum anklicken&7), die du betreten möchtest: '
  modeGlobalArenaLoadLog: '%ARENAS% Arenen mit %KITS% Kits geladen'
  modeGlobalChooseArenaHover: 'In &l%ARENA% &rspielen'
  modeGlobalChoosePlayerCount: '(%AMOUNT% Spieler)'
  modeGlobalCommandsInBedDisabled: '&cDu kannst im Bett keine Kommandos benutzen'
  modeGlobalBattleModeDisabled: '&7Dieser Spielmodus ist aktuell &cdeaktiviert'
  modeGlobalKitArenaCustomLore: '&a%ARENA% &7(&o%MODE%&7) - &b%PLAYER%'
  modeGlobalLeftQueue: '&7Du hast die Warteschlange verlassen'
  modeGlobalNoCommandInGame: '&cDu kannst im Kampf keine Kommandos benutzen'
  modeGlobalNotIdle: '&cDu bist bereits im Spiel oder in einer Warteschlange'
  modeGlobalQueueCooldown: '&cDu hast die Warteschlange/Arena vor kurzem erst verlassen, &7bitte warte noch etwas'
  modeGlobalRandomArena: 'Zufall'
  modeGlobalShowArenaList: '&aGrüne Arenen &7sind aktuell frei, &crote Arenen &7sind belegt: '
  modeGlobalTeleportIntoArenaDenied: '&cDu kannst dich nicht in die Nähe von Arenen teleportieren'
