#HalfminerBattle Config
gameMode:
  global:
    #Disable hunger loss
    noHungerLoss: true
  duel:
    #Broadcast duel wins
    broadcastWin: true
    #Time in seconds until server will broadcast that a dueling player is waiting to be dueled, 0 to disable
    waitingForMatchRemind: 30
    #Max duel time
    gameTime: 300
localization:
  prefix: '&7HalfminerBattle &e>>&r '
  commandClickHover: 'Klicken, um das Kommando auszuführen'
  noPermission: '&cDu hast nicht die Berechtigung dies zu verwenden'
  notAPlayer: 'Dieses Kommando kann nur als Spieler ausgeführt werden'
  playerNotOnline: '&cDer Spieler ist nicht online oder existiert nicht'
  randomArena: 'Zufall'
  adminArenaDoesntExist: '&7Die Arena &c%ARENA% &7existiert nicht'
  adminClearSpawns: '&7Die Spawns für die Arena &a%ARENA% &7wurden entfernt'
  adminCommandUsage: 'Version &6%VERSION%\n&6&lSpielmodus Admin Kommandos:\n &f/hmb <modus>\n&6&lArena Kommandos: \n &f/hmb reload\n /hmb create <mode> <name>\n /hmb remove <mode> <arenaname>\n /hmb setspawn <mode> <arenaname> [spawn]\n /hmb clearspawns <mode> <arenaname>\n /hmb setkit <mode> <arenaname>'
  adminCreate: '&7Die Arena &a%ARENA% &7wurde erstellt. Verwende &6/hmb setspawn <modus> %ARENA% &7um Spawnpunkte setzen'
  adminCreateFailed: '&cDie Arena &e%ARENA%&c existiert bereits'
  adminNotDefined: '&7Der Modus &c%GAMEMODE% &7hat keine administrativen Kommandos'
  adminRemove: '&aDie Arena &e%ARENA%&a wurde entfernt'
  adminSetKit: '&7Das Kit für die Arena &a%ARENA% &7wurde gesetzt'
  adminSetSpawn: '&7Der Spawn für die Arena &a%ARENA% &7wurde gesetzt'
  adminSettingsReloaded: '&aDie Konfiguration wurde neugeladen'
  adminSettingsReloadedError: '&cFehler beim neu laden der Arena Konfiguration, siehe Konsole für weitere Informationen'
  adminUnknownGamemode: '&cUnbekannter Spielmodus'
  modeDuelChooseArena: '&aGib im Chat die Nummer für die Arena ein, auf der du gegen &e%PLAYER%&a spielen willst: '
  modeDuelChooseArenaInvalid: '&cUngültige Auswahl, bitte versuche es erneut'
  modeDuelChooseArenaNoneAvailable: '&7Aktuell sind alle Arenen belegt, ihr werdet automatisch in die nächste freie Arena teleportiert'
  modeDuelChooseArenaRefreshed: '&bDie Auswahl wurde aktualisiert: '
  modeDuelCountdownStart: '&7Das Duell in der Arena &e%ARENA%&7 gegen &c%PLAYER%&7 startet in 5 Sekunden'
  modeDuelGameLost: '&cDu hast das Duell gegen &e%PLAYER%&c verloren'
  modeDuelGameStarting: '&aDer Kampf beginnt!'
  modeDuelGameTime: '&7Das Duell gegen &e%PLAYER%&7 ist unentschieden'
  modeDuelGameWon: '&aDu hast das Duell gegen &e%PLAYER%&a gewonnen'
  modeDuelNotInQueue: '&cDu bist nicht in der Warteschlange'
  modeDuelPartnerChoosingArena: '&e%PLAYER%&7 wählt nun eine Arena aus, das Duell startet gleich'
  modeDuelPlayerWaitingForMatch: '~&e%PLAYER%&7 wartet auf einen Duellpartner. Gib &a/duel match/&7 für ein faires Duell mit gleicher Ausrüstung ein'
  modeDuelQueueRemovedNotTheCause: '&cDein Duellpartner hat die Warteschlange verlassen, womit du auch entfernt wurdest'
  modeDuelRequest: '~&e%PLAYER%&7 hat dir eine Duell Herausforderung geschickt. Gib &6/duel %PLAYER%/ &7ein, um sie zu akzeptieren'
  modeDuelRequestAccepted: '&aDu hast die Herausforderung akzeptiert'
  modeDuelRequestAlreadyOpen: '~&cDu hast bereits eine offene Duell Herausforderung, verwende &6/duel leave/&c zum zurückziehen'
  modeDuelRequestCancel: '&aDeine Herausforderung wurde zurückgezogen'
  modeDuelRequestCancelled: '&e%PLAYER% &7hat seine Herausforderung zurückgezogen'
  modeDuelRequestExempt: '&cDu kannst &e%PLAYER%&c keine Anfragen schicken'
  modeDuelRequesteeNotAvailable: '&e%PLAYER%&c ist bereits in der Warteschlange oder im Spiel'
  modeDuelRequestPending: '&cDu hast bereits eine offene Anfrage abgeschickt'
  modeDuelRequestSent: '~&aDeine Herausforderung wurde an &e%PLAYER%&a geschickt, verwende &6/duel leave/&a zum zurückziehen'
  modeDuelRequestWasAccepted: '&aDeine Anfrage wurde von &e%PLAYER%&a akzeptiert'
  modeDuelRequestYourself: '&cDu kannst dir selber keine Anfrage schicken'
  modeDuelShowHelp: '~&7Faire Duelle mit gleicher Ausrüstung in Arenen\n &e/&eduel <Spielername> - &7&oDuellanfrage schicken\n &e/duel match/ - &7&oDuellpartner finden\n &e/duel leave/ - &7&oWarteschlange verlassen\n &e/duel list/ - &7&oArenaliste anzeigen'
  modeDuelStartingLog: 'Duell startet zwischen %PLAYERA% und %PLAYERB% in Arena %ARENA%'
  modeDuelTimeRunningOut: '&cDas Duell wird in &e%TIME%&c Sekunden abgebrochen'
  modeDuelWinBroadcast: '&a%WINNER% &7hat gegen &c%LOSER% &7in der Arena &e%ARENA% &7gewonnen'
  modeGlobalAddedToQueue: '~&7Du bist nun in der Warteschlange, verwende &6/duel leave/&7 zum verlassen'
  modeGlobalAlreadyInQueue: '~&cDu bist bereits in einer Warteschlange, verwende &6/duel leave/&c zum verlassen'
  modeGlobalGamemodeDisabled: '&cDieser Spielmodus ist aktuell deaktiviert'
  modeGlobalInGame: '&cIm Kampf darfst du keine Kommandos verwenden'
  modeGlobalLeftQueue: '&7Du hast die Warteschlange verlassen'
  modeGlobalQueueCooldown: '&cDu hast die Warteschlange vor kurzem erst verlassen, bitte warte noch etwas'
  modeGlobalShowArenaList: '&aGrüne Arenen&7 sind aktuell frei, &crote Arenen &7sind belegt: '
  modeGlobalTeleportIntoArenaDenied: '&cDu darfst dich nicht in Arenen teleportieren'
