#HalfminerBattle Config
gameMode:
  global:
    #Disable hunger loss
    noHungerLoss: true
    #Time in seconds the queue cooldown will take
    queueCooldownTimeSeconds: 15
    #Distance in blocks from all spawn points in all arenas that must be met to allow the teleport
    teleportSpawnDistance: 10
  duel:
    #Broadcast duel wins
    broadcastWin: true
    #Max duel time
    gameTime: 300
    #Time in seconds until server will broadcast that a dueling player is waiting to be dueled, 0 to disable
    waitingForMatchRemind: 30
localization:
  prefix: '&7Battle &e>>&r '
  commandClickHover: 'Klicken, um das Kommando auszuführen'
  noPermission: '&cDu hast nicht die Berechtigung dies zu verwenden'
  notAPlayer: 'Dieses Kommando kann nur als Spieler ausgeführt werden'
  playerNotOnline: '&cDer Spieler ist nicht online oder existiert nicht'
  randomArena: 'Zufall'
  adminArenaDoesntExist: '&7Die Arena &c%ARENA% &7existiert nicht'
  adminClearSpawns: '&7Der Spawn (oder alle Spawns) für die Arena &a%ARENA% &7wurde entfernt'
  adminCommandUsage: 'HalfminerBattle Version &6%VERSION%\n&6&lSpielmodus Admin Kommandos:\n &f/hmb <modus>\n&6&lArena Kommandos: \n &f/hmb reload\n /hmb create <mode> <name>\n /hmb remove <mode> <arenaname>\n /hmb setspawn <mode> <arenaname> [spawnnumber]\n /hmb removespawn <mode> <arenaname> [spawnnumber]\n /hmb setkit <mode> <arenaname>'
  adminCreate: '~&7Die Arena &a%ARENA% &7wurde erstellt. Verwende &e/hmb setspawn %MODE% %ARENA%/ &7um weitere Spawnpunkte setzen'
  adminCreateFailed: '&7Die Arena &c%ARENA% &7existiert bereits'
  adminNotDefined: '&7Der Modus &c%GAMEMODE% &7hat keine administrativen Kommandos'
  adminRemove: '&7Die Arena &a%ARENA% &7wurde entfernt'
  adminSetKit: '&7Das Kit für die Arena &a%ARENA% &7wurde gesetzt'
  adminSetSpawn: '&7Der Spawn für die Arena &a%ARENA% &7wurde gesetzt'
  adminSettingsReloaded: '&aDie Konfiguration wurde neugeladen'
  adminSettingsReloadedError: '&cFehler beim neu laden der Arena Konfiguration, siehe Konsole für weitere Informationen'
  adminUnknownGamemode: '&cUnbekannter Spielmodus'
  modeDuelChooseArena: '&7Klicke die Arena mit der Maus (&oChat öffnen zum anklicken&7), auf der du gegen &e%PLAYER% &7spielen willst: '
  modeDuelChooseArenaHover: 'In &l%ARENA% &rspielen'
  modeDuelChooseArenaRandom: 'In einer &lzufälligen &rArena spielen\n(Gegner erhält Benachrichtigung)'
  modeDuelChooseArenaInvalid: '&cUngültige Auswahl, bitte versuche es erneut'
  modeDuelChooseArenaNoneAvailable: '&7Aktuell sind alle Arenen belegt, ihr werdet automatisch in die nächste freie Arena teleportiert'
  modeDuelChooseArenaRefreshed: '&7Die Auswahl wurde aktualisiert: '
  modeDuelCountdownStart: '&7Das Duell in der Arena &e%ARENA%&7 gegen &c%PLAYER%&7 startet in 5 Sekunden'
  modeDuelGameLost: '&cDu hast das Duell gegen &e%PLAYER%&c verloren'
  modeDuelGameStarting: '&aDer Kampf beginnt!'
  modeDuelGameTime: '&7Das Duell gegen &e%PLAYER%&7 ist unentschieden'
  modeDuelGameWon: '&aDu hast das Duell gegen &e%PLAYER%&a gewonnen'
  modeDuelNotInQueue: '&cDu bist nicht in der Warteschlange'
  modeDuelOpponentChoseRandom: '&e%PLAYER% &7hat eine &lzufällige Arena &7ausgesucht'
  modeDuelPartnerChoosingArena: '&e%PLAYER%&7 wählt nun eine Arena aus, das Duell startet gleich'
  modeDuelPlayerWaitingForMatch: '~&e%PLAYER%&7 wartet auf einen Duellpartner. Gib &a/duel match/&7 für ein faires Duell mit gleicher Ausrüstung ein'
  modeDuelQueueRemovedNotTheCause: '&cDein Duellpartner hat die Warteschlange verlassen, womit du auch entfernt wurdest'
  modeDuelRequest: '~&e%PLAYER%&7 hat dir eine Duell Herausforderung geschickt. Gib &a/duel %PLAYER%/ &7ein, um sie zu akzeptieren'
  modeDuelRequestAccepted: '&7Du hast die Herausforderung &aakzeptiert'
  modeDuelRequestCancel: '&7Deine Herausforderung wurde zurückgezogen'
  modeDuelRequestCancelled: '&e%PLAYER% &7hat seine Herausforderung &czurückgezogen'
  modeDuelRequestExempt: '&7Du kannst &c%PLAYER% &7keine Anfragen schicken'
  modeDuelRequesteeNotAvailable: '&e%PLAYER%&c ist bereits in der Warteschlange oder im Spiel'
  modeDuelRequestSent: '~&7Deine Herausforderung wurde an &e%PLAYER% &7geschickt, verwende &a/duel leave/ &7zum zurückziehen'
  modeDuelRequestWasAccepted: '&7Deine Anfrage wurde von &e%PLAYER% &aakzeptiert'
  modeDuelRequestWasWaitingForMatch: '&e%PLAYER% &7hat auf einen Partner gewartet, deine Anfrage wurde daher akzeptiert'
  modeDuelRequestYourself: '&cDu kannst dir selber keine Anfrage schicken'
  modeDuelShowHelp: '~&7Faire Duelle mit gleicher Ausrüstung in Arenen\n &e/&eduel <Spielername> - &7&oDuellanfrage schicken\n &a/duel match/ - &7&oDuellpartner finden\n &a/duel leave/ - &7&oWarteschlange verlassen\n &a/duel list/ - &7&oArenaliste anzeigen'
  modeDuelShowPartnerTitle: ' \n&fDuellpartner: &6&l%PLAYER%'
  modeDuelStartingLog: 'Duell startet zwischen %PLAYERA% und %PLAYERB% in Arena %ARENA%'
  modeDuelTimeRunningOut: '&cDas Duell wird in 5 Sekunden abgebrochen'
  modeDuelTitleCountdown: 'Duell startet in...\n&e&l%TIME% &rSekunden'
  modeDuelTitleStart: ' \n&6&lStart!'
  modeDuelWinBroadcast: '&a%WINNER% &7hat gegen &c%LOSER% &7in der Arena &e%ARENA% &7gewonnen'
  modeGlobalAddedToQueue: '~&7Du bist nun in der Warteschlange, verwende &a/duel leave/ &7zum verlassen'
  modeGlobalAlreadyInQueue: '~&cDu bist bereits in einer Warteschlange, &7verwende &a/duel leave/ &7zum verlassen'
  modeGlobalArenaLoadLog: '%ARENAS% Arenen und %KITS% Kits geladen'
  modeGlobalGamemodeDisabled: '&7Dieser Spielmodus ist aktuell &cdeaktiviert'
  modeGlobalInGame: '&cDu kannst im Kampf keine Kommandos benutzen'
  modeGlobalKitArenaCustomLore: '&a%ARENA% &7(&o%MODE%&7) | &b%PLAYER%'
  modeGlobalLeftQueue: '&7Du hast die Warteschlange verlassen'
  modeGlobalQueueCooldown: '&cDu hast die Warteschlange vor kurzem erst verlassen, &7bitte warte noch etwas'
  modeGlobalShowArenaList: '&aGrüne Arenen &7sind aktuell frei, &crote Arenen &7sind belegt: '
  modeGlobalTeleportIntoArenaDenied: '&cDu kannst dich nicht in die Nähe von Arenen teleportieren'
