name: HalfminerBattle
version: ${project.version}
description: Halfminer.de Battle Arena
author: Kakifrucht
website: https://halfminer.de
api-version: '1.14'

main: de.halfminer.hmb.HalfminerBattle
depend: [HalfminerSystem]

commands:
  duel:
    description: Duel mode base command
    aliases: [1vs1, duell, 1v1]
    permission: hmb.mode.duel.use
  ffa:
    description: Free for all mode base command
    aliases: [pvp]
    permission: hmb.mode.ffa.use
  hmb:
    description: Access admin commands per battle mode, add, remove and edit arenas
    aliases: [hmbattle, hbattle, halfminerbattle, global]
    permission: hmb.admin
permissions:
  hmb.*:
    default: op
    description: Access to everything
    children:
      hmb.admin: true
      hmb.mode.*: true
  hmb.mode.*:
    description: Access to all battle modes and global permissions
    children:
      hmb.mode.duel: true
      hmb.mode.ffa: true
      hmb.mode.global: true
  hmb.mode.duel:
    description: Access to all duel functionality
    children:
      hmb.mode.duel.exempt.request: true
      hmb.mode.duel.use: true
  hmb.mode.ffa:
    description: Access to all FFA functionality
    children:
      hmb.mode.ffa.use: true
  hmb.mode.global:
    description: Access to all global functionality
    children:
      hmb.mode.global.bypass.commands: true
      hmb.mode.global.bypass.teleportintoarena: true
  hmb.mode.duel.use:
    default: true
    description: Access to duel mode
  hmb.mode.ffa.use:
    default: true
    description: Access to FFA mode
  hmb.admin:
    description: Administrative permission, access to /hmb
  hmb.mode.duel.exempt.request:
    description: Exempt players cannot be duel requested
  hmb.mode.global.bypass.commands:
    description: Bypass command protection while in battle
  hmb.mode.global.bypass.teleportintoarena:
    description: Bypass the teleport protection into arenas
