name: HalfminerBattle
version: ${project.version}
description: Halfminer.de Battle Arena
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hmb.HalfminerBattle
depend: [HalfminerSystem]

commands:
  duel:
    description: Duel mode base command
    usage: /duel <subcommand/playername>
    aliases: [1vs1, duell, pvp, 1v1]
  hmb:
    description: Access admin commands per gamemode, add, remove and edit arenas)
    usage: /hmb <subcommand> [argument]
    aliases: [hmbattle, hbattle, halfminerbattle, global]
permissions:
  hmb.*:
    default: op
    description: Access to everything
    children:
      hmb.admin: true
      hmb.mode.*: true
  hmb.mode.*:
    description: Access to all gamemodes and advanced permissions
    children:
      hmb.mode.duel: true
      hmb.global.bypass.teleportintoarena: true
  hmb.mode.duel:
    description: Access to all duel functionality
    children:
      hmb.mode.duel.exempt.request: true
      hmb.mode.duel.use: true
  hmb.mode.duel.use:
    default: true
    description: Access to duel mode
  hmb.admin:
    description: Administrative permission, access to /hmb
  hmb.mode.duel.exempt.request:
    description: Exempt players cannot be duel requested
  hmb.global.bypass.teleportintoarena:
    description: Bypass the teleport protection into arenas