#HalfminerSystem Config
handler:
  storage:
    #Time in minutes the storage will be autosaving
    autoSaveMinutes: 15
  teleport:
    #Time in seconds players cannot move before being teleported
    cooldownSeconds: 3
#Use '&' as color code
#Lines starting with '~' will be parsed to make commands clickable, close the command with another '/'
#Messages can be removed by simply setting the message to nothing ('')
localization:
  prefix: '&7%PREFIX% &e>>&r '
  commandClickHover: 'Klicken, um das Kommando auszuführen'
  consoleName: 'Konsole'
  errorOccurred: '&cEin Fehler ist aufgetreten, bitte wende dich an ein Teammitglied'
  lineSeparator: '&e&m------------------------------------------------\n'
  noPermission: '&cDu hast nicht die Berechtigung dies zu verwenden'
  notAPlayer: 'Dieses Kommando kann nur als Spieler ausgeführt werden'
  playerDoesNotExist: '&cDieser Spieler existiert nicht'
  playerNotOnline: '&cDieser Spieler ist nicht online'
  cacheActionProbabilityContainerError: 'Fehler beim parsen der Wahrscheinlichkeitstabelle: %TYPE% in Zeile %LINE%'
  cacheActionProbabilityContainerNoActions: 'Es konnte keine Aktion geparsed werden, füge leere Aktion hinzu...'
  cacheCustomActionCommandNotFound: 'Das Kommando existiert nicht oder konnte nicht ausgeführt werden, breche ab: %COMMAND%'
  cacheCustomActionGiveItemError: 'Der Gegenstand %ITEM% konnte nicht gegeben werden, breche ab, Grund: %REASON%'
  cacheCustomActionParseError: 'Fehler beim parsen der Aktion %NAME%: %TYPE% in Zeile %LINE%'
  cacheCustomActionParseErrorNoLine: 'Fehler beim parsen der Aktion %NAME%: %TYPE%'
  cacheCustomitemCacheInvalidKey: 'Der Schlüssel %KEY% ist ungültig'
  cacheCustomitemCacheInvalidParameter: 'Der für den Schlüssel "%KEY%" übergebene Parameter "%PARAMETER%" ist ungültig, überspringe...'
  cacheCustomitemCacheLogSuccess: 'Gebe %PLAYER% %AMOUNT% mal %ITEMNAME%'
  hanHooksLoadChatFailed: 'Vault Chat konnte nicht gefunden werden'
  hanStorageCacheCouldNotCreate: 'Die Datei konnte nicht erstellt werden'
  hanStorageCacheCouldNotRead: 'Die Datei konnte nicht gelesen werden'
  hanStorageCacheCreate: 'Die Datei %FILENAME% wurde erstellt'
  hanStorageSaveSuccessful: 'Die Daten wurden gespeichert'
  hanStorageSaveUnsuccessful: 'Die Daten konnten nicht gespeichert werden'
  hanTeleportBar: 'Teleport im Gange, bleibe still stehen...'
  hanTeleportDone: '&7Teleportiere...'
  hanTeleportMoved: '&cTeleport abgebrochen, du hast dich bewegt'
  hanTeleportPending: '&cDu hast bereits einen offenen Teleport, bitte warte'
  hanTeleportStart: '&7Bewege dich nicht, der Teleport startet in &a%TIME% &7Sekunden'
  utilInvalidMaterial: 'Das Material %MATERIAL% existiert nicht'
