name: HalfminerSystem
version: ${project.version}
description: Halfminer.de Plugin API
author: Kakifrucht
website: https://halfminer.de
api-version: '1.14'

main: de.halfminer.hms.HalfminerSystem
softdepend: [Essentials, Vault]

commands:
  hms:
    description: HalfminerSystem base command showing version information and reloading every hooked plugin
    aliases: [halfminer, halfminersystem, hsystem, hmsystem]
permissions:
  hms.*:
    description: Access to all permission
    default: op
    children:
      hms.command: true
      hms.noteleporttimer: true
  hms.level.*:
    description: Grants highest player level
    default: op
    children:
      hms.level.0: true
      hms.level.1: true
      hms.level.2: true
      hms.level.3: true
      hms.level.4: true
      hms.level.5: true
      hms.level.6: true
  hms.level.0:
    default: true
    description: Access to features restricted to level 0
  hms.command:
    description: Access to hms command
  hms.level.1:
    description: Access to commands restricted to level 1
  hms.level.2:
    description: Access to commands restricted to level 2
  hms.level.3:
    description: Access to commands restricted to level 3
  hms.level.4:
    description: Access to commands restricted to level 4
  hms.level.5:
    description: Access to commands restricted to level 5
  hms.level.6:
    description: Access to commands restricted to level 6
  hms.noteleporttimer:
    description: Access to administrative commands
