name: HalfminerSystem
version: ${project.version}
description: Halfminer.de Plugin API
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hms.HalfminerSystem
softdepend: [Essentials, Vault]

commands:
  ?:
    description: Bukkit override, protects from viewing all commands
    aliases: [alias]
permissions:
  hms.*:
    description: Access to all permission
    default: op
    children:
      hms.noteleporttimer: true
  hms.noteleporttimer:
    description: Access to administrative commands
