#HalfminerLand Config
# Define commands that are blocked if a player is in a land of another player and wasn't added as a friend
# Automatically blocks all registered command aliases and can also only block subcommands by adding arguments
#  Bypass permission is 'hml.bypass.cmd'
blockedCmds:
  - sethome
  - tpaccept
  - tpahere
buyLimits:
  # Specify minimum x and z coordinates to buy the land
  #  Format: <Worldname>, <minimumxandz>
  # Land that already contains a WorldGuard region is never buyable
  # Set <minimumxandz> to -1 to disable land buying in given world completely
  worldRestrictions:
  - world, 512
  - world_nether, 112
  - world_the_end, 112
  - world_disabled, -1
fly:
  # Price to fly
  cost: 10.0
  # How long a player can fly for the given cost
  durationSeconds: 600
# How many players can be added as friend per land
#  Bypass permission is 'hml.bypass.friendlimit'
friendLimit: 6
# After how many days of inactivity land should be set abandoned
landAbandonedAfterDays: 21
# How likely should a player that owns no land yet receive a message about it on block placement
# Set percentage as decimal, e.g. on place in 1% of the cases is 0.01
landNotProtectedMessagePercentage: 0.01
priceFormula:
  # Minimum price, first land is always free
  minPrice: 2
  # Formula: price = minPrice * factor^landsOwned
  factor: 1.45
  # Max price per land
  limit: 250000
  # Set refund multiplier as a double between 0 and 1
  sellRefundMultiplier: 0.8
# Will be used as owner name for land bought for the server via /land buy server
serverName: 'Halfminer.de'
teleport:
  name:
    # Teleport names that cannot be bought, teleport names must be between 4 and 15 characters
    #  Bypass permission is 'hml.bypass.teleportblacklist'
    blacklist:
    - admin
    - adminshop
    - shop
    # Minimum teleport name length, bypass permission is 'hml.bypass.teleportlength'
    minLength: 4
    # Maximum teleport name length, bypass permission is 'hml.bypass.teleportlength'
    maxLength: 15
  # If set to true players can steal a teleport name when the land is currently abandoned
  allowStealingAbandoned: false
  # Specify how many teleports a player can buy via /land teleport buy,
  #  Bypass permission is 'hml.cmd.teleport.unlimited'
  maxAmount: 3
  # Specify the price per teleport
  price: 10
  # Specify the price to move the teleport
  priceMove: 5
  # Specify which material to use when server land was pinned
  pinnedTeleportServerLandMaterial: DIAMOND_BLOCK
# Use '&' as color code
# Lines starting with '~' will be parsed to make commands clickable, close the command with another '/' (like /help/)
# Messages can be removed by simply setting the message to nothing ('')
localization:
  prefix: '&7Land &e>>&r '
  boardShowChunkBar: 'Das Land wird aktuell durch Partikel markiert'
  cmdBuyAlreadyOwned: '&7Dieses Land gehört &b%PLAYER% &7und steht daher nicht zum Verkauf'
  landNotOwned: '&cDieses Land gehört dir nicht'
  notEnoughMoney: '&cDu hast nicht genügend Geld, du benötigst &e%COST% &cHCs'
  noLandOwned: '&cDu besitzt kein Land'
  noLandOwnedPlayer: '&c%PLAYER% &7besitzt kein Land'
  noOwner: 'Frei'
  teleportNotExist: '&cDieser Teleport existiert nicht'
  usage: '~ \n&e&m-------------&c&l HalfLand Kommandos &e&m-------------\n&7Aktuelles Land kaufen: &a/land buy/\n&7Aktuelles Land verkaufen: &a/land sell/\n&7Informationen über aktuelles Land: &a/land info/\n&7Freunden Baurechte geben/nehmen: &a/land friend/\n&7Teleportpunkte kaufen/setzen: &a/land teleport/\n&7Alle eigenen Länder anzeigen: &a/land list/\n&7Auf eigenem Gebiet fliegen: &a/land fly/\n&7Zu einem Teleportpunkt teleportieren: &a/landtp/ [Teleport]\n&e&m----------------------------------------------'
  cmdBuyAlreadyOwnedSelf: '&7Dieses Land gehört dir bereits'
  cmdBuyConfirm: '~&7Du bist im Begriff das mit Partikeln markierte Land (Chunk von ganz oben bis ganz unten) für &a%COST% &7HCs zu kaufen, wiederhole das Kommando &a/land buy/ &7zum bestätigen'
  cmdBuyConfirmFree: '~&7Du bist im Begriff das mit Partikeln markierte Land (Chunk von ganz oben bis ganz unten) als kostenloses Freiland zu kaufen, wiederhole das Kommando &a/land buy/ &7zum bestätigen'
  cmdBuyNotBuyable: '&cDieses Land steht nicht zum Verkauf'
  cmdBuyNotBuyableCoordinate: '&cDieses Land steht nicht zum Verkauf, die minimalen Koordinaten zum Landkauf fangen bei &axz%MINIMUMCOORDS% &can'
  cmdBuyNotBuyableNotVacant: '&cDu kannst Land nur kaufen wenn du zum Kaufzeitpunkt der einzige Spieler auf dem Land bist'
  cmdBuyNotBuyableWorld: '&cDieses Land steht nicht zum Verkauf, du kannst in dieser Welt kein Land kaufen'
  cmdBuySuccess: '~&7Du hast dieses Land erfolgreich für &a&l%COST% HCs &7gekauft. Es ist nun vollständig gesichert und kann nicht gegriefed werden. &c&lAchtung: &7Wenn du 21 Tage offline warst kann das Gebiet wieder geklaut und gegriefed werden.\n \n Freunde hinzufügen: &a/land friend add <Spieler>\n &7Öffentlichen Teleport kaufen: &a/land teleport buy <Teleport>\n &7Land verkaufen: &a/land sell/'
  cmdBuySuccessAsServer: '&7Du hast dieses Land erfolgreich als Serverland gekauft, es wird nicht als verlassen markiert'
  cmdBuySuccessFree: '&7Du hast dieses Land erfolgreich als Freiland gekauft und &b%FREELANDSOWNED%&7/&o%FREELANDSMAX% &7deiner freien Länder benutzt, du kannst es jederzeit verkaufen und stattdessen ein anderes Gebiet als Freiland kaufen'
  cmdFlyAlreadyFlying: '&cDu kannst bereits fliegen'
  cmdFlyDisable: '&7Flugmodus &cbeendet&7, deine verbleibende Flugzeit beträgt &a%TIME% &7Sekunden'
  cmdFlyEnable: '~&7Flugmodus &aaktiviert&7, du kannst nun auf deinem eigenem Grundstück für &a%TIME% &7Sekunden fliegen, der Flug wird automatisch verlängert, sofern er nicht vorher mit &a/land fly/ &7beendet wird'
  cmdFlyNotEnoughMoney: '&7Du hast nicht genügend Geld, fliegen kostet &c%COST% HCs &7je &o%TIME% &7Sekunden'
  cmdFlyNotOwned: '&cDu kannst nur auf eigenem Land anfangen zu fliegen'
  cmdFlyServerDisabled: '&cFliegen ist auf dem Server deaktiviert'
  cmdFriendAddSuccess: '~&a%PLAYER% &7wurde erfolgreich als Freund zum aktuellen Land hinzugefügt. Bitte beachte das &cgriefen und bestehlen erlaubt ist&7, traue keinen fremden Spielern!\n \n Als Freund entfernen: &a/land friend remove %PLAYER%/&7\n Zu allen Gebieten hinzufügen: &a/land friend add %PLAYER% all/'
  cmdFriendAddSuccessAll: '~&a%PLAYER% &7wurde erfolgreich als Freund zu &lall deinen &b&l%COUNT% &7&lLändern hinzugefügt&7. Bitte beachte das &cgriefen und bestehlen erlaubt ist&7, traue keinen Fremden Spielern!\n \n Als Freund entfernen: &a/land friend remove %PLAYER% all/'
  cmdFriendAddSuccessConnected: '~&a%PLAYER% &7wurde erfolgreich als Freund zu &b&l%COUNT% &7&lLändern, die mit deinem aktuellen Land verbunden sind, hinzugefügt&7. Bitte beachte das &cgriefen und bestehlen erlaubt ist&7, traue keinen Fremden Spielern!\n \n Als Freund entfernen: &a/land friend remove %PLAYER% connected/'
  cmdFriendAddFailure: '~&b%PLAYER% &cist bereits als Freund zu deinem aktuellen Land hinzugefügt, verwende &a/land friend remove %PLAYER%/ &cum ihn zu entfernen'
  cmdFriendAddFailureAll: '~&b%PLAYER% &cist bereits als Freund all deiner Länder hinzugefügt, verwende &a/land friend remove %PLAYER% all/ &cum ihn zu entfernen'
  cmdFriendAddFailureConnected: '&b%PLAYER% &ckonnte von keinem deiner verbundenen Länder als Freund hinzugefügt werden'
  cmdFriendAddLimitReached: '&cDu kannst nur &a%LIMIT% &cFreunde pro Land hinzufügen'
  cmdFriendRemoveSuccess: '&a%PLAYER% &7wurde erfolgreich als Freund von deinem aktuellen Land entfernt'
  cmdFriendRemoveSuccessAll: '&a%PLAYER% &7wurde erfolgreich als Freund von all deinen &b%COUNT% &7Ländern entfernt'
  cmdFriendRemoveSuccessConnected: '&a%PLAYER% &7wurde erfolgreich als Freund von deinen &b%COUNT% &7Ländern, die mit diesem Land verbunden sind, entfernt'
  cmdFriendRemoveFailure: '&a%PLAYER% &cist kein Freund von deinem aktuellen Land'
  cmdFriendRemoveFailureAll: '&cDu hast &b%PLAYER% &czu keinem deiner Länder als Freund hinzugefügt'
  cmdFriendRemoveFailureConnected: '&b%PLAYER% &ckonnte von keinem deiner mit diesem Land verbundenen Länder als Freund entfernt werden'
  cmdFriendSelf: '&cDu kannst dich nicht selber als Freund hinzufügen/entfernen'
  cmdFriendUsage: ' \n&e&m-------------&c&l Freunde Kommandos &e&m-------------\n&7Freund hinzufügen: &a/land friend add <Spieler>\n&7Freund entfernen: &a/land friend remove <Spieler>\n \n&7Freunde werden zu dem Land hinzugefügt, auf dem du aktuell stehst. Sie erhalten dadurch volle Baurechte, &cvertraue keinen fremden Spielern! &7Hänge &a&oall &7hinten an eines der Kommandos um den angegebenen Spieler zu all deinen Ländern hinzuzufügen/entfernen. Hänge &a&oconnected &7hinten an eines der Kommandos um den angegeben Spieler zu all deinen mit diesem Land verbundenen Ländern hinzuzufügen.\n&e&m----------------------------------------------'
  cmdHmlCustomTitleNoneSet: '&cDieses Land hat keinen Titel'
  cmdHmlCustomTitleNotOwned: '&cDieses Land hat keinen Besitzer'
  cmdHmlCustomTitleRemoved: '&7Folgender Titel wurde &aerfolgreich &7entfernt:\n&r%TITLE%'
  cmdHmlCustomTitleSet: '&7Folgender Title wurde &aerfolgreich &7gesetzt:\n&r%TITLE%'
  cmdHmlFlyTime: '&7Verbleibende Flugzeit für &e%PLAYER%&7: &a%TIMELEFT% &7&oSekunden'
  cmdHmlFlyTimeSet: '&7Verbleibende Flugzeit für &e%PLAYER%&7 wurde erfolgreich von &b%TIMELEFT% &7auf &a%TIMESET% &7Sekunden gesetzt'
  cmdHmlFreeSet: '&e%PLAYER%''s &7maximale freie Länder wurde von &b%CURRENTFREE% &7auf &o%HASFREE%&7/&a%SETFREE% &7gesetzt'
  cmdHmlFreeShow: '&e%PLAYER% &7hat &b%HASFREE%&7/&o%CURRENTFREE% &7freien Ländern'
  cmdHmlPinTpNotFound: '&cDieser Teleportpunkt existiert nicht'
  cmdHmlPinTpPinned: '&a%TELEPORT% &7wurde erfolgreich angepinnt'
  cmdHmlPinTpRemoved: '&a%TELEPORT% &7wurde erfolgreich entpinnt'
  cmdHmlPinTpUnknownMaterial: '&cDas Material existiert nicht'
  cmdHmlRefreshDone: '&aAlle Regionen wurden erneuert'
  cmdHmlRefreshStarted: '&7Starte WorldGuard Regions Erneuerung, dies kann kurz dauern...'
  cmdHmlSave: '&aDie Land Daten wurden gespeichert'
  cmdHmlStatus: '&6&lLänder mit Besitzer:\n &7Gesamt: &b%TOTALLANDS% &7(&okostenlos&7: &b%TOTALFREE%&7, &oServer&7: &b%TOTALSERVER%&7, &overlassen&7: &b%TOTALABANDONED%&7)\n Teleportpunkte: &b%TOTALTELEPORTS%\n &7Je Welt: %TOTALWORLDLIST%'
  cmdHmlStatusWorldListEntry: '&e%WORLD%&7-&b%AMOUNT%'
  cmdHmlUsage: 'HalfminerLand Version &6%VERSION%\n&6&lLand Admin Kommandos:&f\n /hml reload\n /hml save\n /hml status\n /hml customtitle <Titel|-c>\n /hml forcewgrefresh\n /hml flytime <Spieler> [Zeit]\n /hml free <Spieler> [Wert]\n /hml pintp <Teleport>\n /land buy server\n /land sell force\n /land teleport delete <Teleport>\n /land list <Spieler|-s>'
  cmdInfoFree: '~&7Dieses Land ist frei, verwende &a/land buy/ &7zum kaufen'
  cmdInfoNoFriends: '&fKeine hinzugefügt'
  cmdInfoNoTeleport: '&fKeiner gesetzt'
  cmdInfoOwned: '&7Besitzer: &6&l%OWNER% &7(besitzt &a%OWNEDLANDS% &7Länder)\n &7Freunde: &6%FRIENDS%\n &7Teleportpunkt: &a%TELEPORT%'
  cmdInfoOwnedAbandoned: '&7Besitzer: &8&l%OWNER% &7(besitzt &a%OWNEDLANDS% &7Länder, &oLand ist verlassen)\n &7Freunde: &6%FRIENDS%\n &7Teleportpunkt: &a%TELEPORT%'
  cmdLandtpIsAbandoned: '&cDieses Land ist verlassen und der Teleport damit nicht mehr zugänglich'
  cmdLandtpIsAbandonedSteal: '~&cDieses Land ist verlassen und der Teleport damit nicht mehr zugänglich&7, du kannst den Teleportpunkt mit &a/land teleport buy %NAME%/ &7klauen'
  cmdLandtpMenuEmpty: '&7Keiner der Spieler, die aktuell online sind, stellt einen Teleportpunkt aus, verwende stattdessen &a/landtp <Teleport> &7um dich zu einem dir bereits bekannten Ort zu teleportieren'
  cmdLandtpMenuItemFormat: '&6&l%TELEPORTFRIENDLY%|&r|&a/landtp %TELEPORT%|&7von &e%PLAYER%'
  cmdLandtpMenuItemFormatNotShown: '&f&6&l%TELEPORTFRIENDLY%|&r|&a/landtp %TELEPORT%|&7&oDieser Teleport ist nicht|&7&oausgestellt und wird|&7&onur dir angezeigt'
  cmdLandtpMenuItemFormatPinned: '&6&l%TELEPORTFRIENDLY%|&e✪ Angepinnt|&r|&a/landtp %TELEPORT%|&7von &e%PLAYER%'
  cmdLandtpMenuTitle: '&4&lLand Teleporter &8(/landtp)'
  cmdLandtpOwnTimer: '&7Da du dich zu deinem eigenen Teleportpunkt teleportierst ist die Wartezeit vor dem Teleport erhöht, um die Verwendung als Ersatzhomes einzuschränken'
  cmdListAsText: '&a%PLAYER% &7besitzt &b%LANDAMOUNT% &7Länder.\n Länderliste: %LANDLIST%'
  cmdListAsTextFormat: '&6%WORLD%&7|&ex%X%&7|&ez%Z%'
  cmdListAsTextFormatTeleport: '&6%WORLD%&7|&ex%X%&7|&ez%Z%&7|&etp&b&o%TELEPORT%'
  cmdListMenuLandEntry: '&fX: &a%X% &fZ: &a%Z%|&r|&7Welt: &a%WORLD%'
  cmdListMenuLandEntryTeleport: '&fX: &a%X% &fZ: &a%Z%|&r|&7Welt: &a%WORLD%|&7Teleport: &a%TELEPORT%'
  cmdListMenuTitle: '&8Länder von &4&l%PLAYER%'
  cmdListMenuTitleAbandoned: '&8&oVerlassene &8Länder von &4&l%PLAYER%'
  cmdSellConfirm: '~&7Du bist im Begriff das mit Partikeln markierte Land für &a%COST% &7HCs zu verkaufen, wiederhole das Kommando &a/land sell/ &7zum bestätigen'
  cmdSellConfirmFree: '~&7Das mit Partikeln markierte Land ist ein kostenloses Freiland, welches du jederzeit umplatzieren kannst, wiederhole das Kommando &a/land sell/ &7um den Verkauf zu bestätigen'
  cmdSellForceNotify: '&cDein Land bei &e%LAND% &cwurde von &b%FORCINGPLAYER% &czwangsverkauft'
  cmdSellForceUsage: '~&cDieses Land gehört dir nicht, verwende &a/land sell force/ &cum den Verkauf zu erzwingen'
  cmdSellHasTeleport: '~&cDieses Land hat einen Teleportpunkt, verschiebe ihn vor dem Verkauf auf ein anderes Land mit &a/land teleport set %TELEPORT%/ &coder entferne ihn mit &a/land teleport delete %TELEPORT%/'
  cmdSellOthersOnLand: '&cZum Verkaufen darf sich kein anderer Spieler auf dem Land befinden'
  cmdSellSuccess: '&aDu hast dieses Land erfolgreich für &l%COST% HCs &averkauft, &7es kann nun von jedem Spieler bebaut und gekauft werden'
  cmdSellSuccessForce: '&7Das Land von &e%LANDOWNER% &7steht nun wieder zur Verfügung, der Besitzer hätte bei einem Verkauf &b%COST% HC''s &7erhalten'
  cmdSellSuccessFree: '&aDu hast dieses Freiland erfolgreich wieder freigegeben, &7es kann nun von jedem Spieler bebaut und gekauft werden'
  cmdSellSuccessServer: '&7Das Serverland wurde erfolgreich wieder &cfreigegeben'
  cmdTeleportBuyAlreadyExists: '&cDieser Teleportpunkt ist bereits vergeben'
  cmdTeleportBuyAlreadyExistsOwned: '~&cDieser Teleportpunkt ist bereits vergeben, setze ihn neu mit &a/land teleport set %TELEPORT%/'
  cmdTeleportBuyBlacklisted: '&cDieser Teleportpunkt steht nicht zum Verkauf, bitte wähle einen anderen Namen'
  cmdTeleportBuyLimitReached: '&cDu hast die maximale Anzahl an Teleportpunkten (Limit: &a%LIMIT%&c) bereits erreicht'
  cmdTeleportBuyNameFormat: '&cDer Teleportpunkt muss zwischen %MINLENGTH% und %MAXLENGTH% Zeichen enthalten und darf keine Sonderzeichen enthalten'
  cmdTeleportBuySuccess: '~&7Du hast den Teleportpunkt &a%TELEPORT% &7erfolgreich für &b&l%COST% HCs &7gekauft, welcher über &a/landtp %TELEPORT%/ &7öffentlich erreichbar ist. &c&lAchtung: &7Beachte unbedingt die &a/regeln/ &7bezüglich Teleportpunkten (Kurzfassung: Sichere Umgebung schaffen, keine Fallen, keine Lava Kills, ...)'
  cmdTeleportDeleteSuccess: '&7Du hast den Teleportpunkt &e%TELEPORT% &7erfolgreich entfernt'
  cmdTeleportLandAlreadyHasTeleport: '&cDieses Land hat bereits einen Teleportpunkt (&e%TELEPORT%&c)'
  cmdTeleportNotOwned: '&cDieser Teleportpunkt gehört dir nicht'
  cmdTeleportSetSuccess: '&7Du hast den Teleportpunkt &e%TELEPORT% &7erfolgreich für &b&l%COST% HCs &7verschoben'
  cmdTeleportShow: '~&7Dein Teleportpunkt &e%TELEPORT% &7erscheint nun, solange du online bist, öffentlich für alle Spieler im &a/landtp/ &7Menü'
  cmdTeleportShowUnset: '~&7Dein Teleportpunkt &e%TELEPORT% &7wird nicht mehr für alle Spieler unter &a/landtp/ &7angezeigt'
  cmdTeleportUsage: '~ \n&e&m-------------&c&l Teleport Kommandos &e&m-------------\n&7Teleport Kaufen (kostet 10 HCs): &a/land teleport buy <Teleport>\n&7Teleport umsetzen (kostet 5 HCs): &a/land teleport set <Teleport>\n&7Teleport ausstellen: &a/land teleport show <Teleport>\n&7Teleport löschen: &a/land teleport delete <Teleport>\n \n&7Der Teleportname darf beliebig sein, aber nicht Vulgär (Chatregeln beachten). Er ist für alle Spieler unter &a/landtp <Teleport> &7zugänglich. All deine Teleportpunkte, sowie alle ausgestellten Teleportpunkte von anderen online Spielern, erscheinen unter &a/landtp/&7.\n&e&m----------------------------------------------'
  flyBoardDisableAfk: '&cDein Flug wurde nicht verlängert, da du abwesend bist'
  flyBoardDisableForce: '~&7Flugmodus beendet, bitte reaktiviere ihn bei Bedarf mit &a/land fly/'
  flyBoardDisableNotEnoughMoney: '&cFlugzeit abgelaufen, du hast nicht genügend Geld um weiterzufliegen'
  flyBoardRenewed: '~&7Deine Flugzeit wurde um &a%TIME% &7Sekunden für &b%COST% HCs &7verlängert, verwende &a/land fly/ &7um den Flugmodus zu deaktivieren'
  listenerBlockBreakBlocked: '&cDu kannst auf dem Land von &a%OWNER% &ckeine Blöcke brechen'
  listenerBlockPlaceBlocked: '&cDu kannst auf dem Land von &a%OWNER% &ckeine Blöcke platzieren'
  listenerCmdBlocked: '&cDu kannst dieses Kommando auf dem Land von &a%OWNER% &cnicht verwenden'
  listenerFlyPvPDisabled: '&7Flugmodus deaktiviert, da du im Kampf bist, deine verbleibende Flugzeit beträgt &a%TIME% &7Sekunden'
  listenerFormatSpacer: ' &7|&f '
  listenerFormatTitle: ' \n%PVPLINE%%SPACER%%OWNERLINE%'
  listenerLandUnabandoned: '&7Da dein letzter Login länger als 21 Tage her war wurde dein Land zwischenzeitlich als verlassen markiert und war damit ungeschützt, &a%COUNT% &7deiner Länder sind nun wieder geschützt'
  listenerOwnerFree: '&aFreies Land'
  listenerOwnerOwned: 'Landbesitzer: &b&l%OWNER%'
  listenerOwnerOwnedAbandoned: 'Landbesitzer: &8%OWNER% &7(Verlassen)'
  listenerPvPOff: '&aPvP aus'
  listenerPvPOn: '&cPvP an'
  listenerUnprotectedLandMessage: '~&7Du baust aktuell auf ungeschütztem Land, sichere dein erstes Land &ekostenlos &7vor Griefing und Diebstahl mit dem Kommando &a/land buy/'
