name: HalfminerLand
version: ${project.version}
description: Halfminer.de land protection and management
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hml.HalfminerLand
depend: [HalfminerSystem, Essentials, WorldGuard, Factions]

commands:
  land:
    description: Base command
    aliases: [claim, sichern, gebiet]
  landtp:
    description: Teleport to a land with a set teleport point
    aliases: [warpland, warpl]

permissions:
  hml.*:
    description: Access to all permissions
    default: op
    children:
      - hml.bypass.*
      - hml.cmd.buy
      - hml.cmd.free
      - hml.cmd.friend
      - hml.cmd.info
      - hml.cmd.landtp
      - hml.cmd.own
      - hml.cmd.reload
      - hml.cmd.sell
      - hml.cmd.teleport
      - hml.cmd.teleport.deleteothers
      - hml.cmd.teleport.unlimited
  hml.bypass.*:
    description: Access to all bypass permissions
    children:
      - hml.bypass.breakplace
      - hml.bypass.cmd
      - hml.bypass.friendlimit
  hml.bypass.breakplace:
    description: Bypasses block break and placement protection
  hml.bypass.friendlimit:
    description: Bypasses the friend limit per land
  hml.bypass.cmd:
    description: Bypasses command block list in owned land
  hml.cmd.buy:
    description: Grants access to /land buy command
    default: true
  hml.cmd.free:
    description: Grants access to /land free command
  hml.cmd.friend:
    description: Grants access to /land friend command
    default: true
  hml.cmd.info:
    description: Grants access to /land info command
    default: true
  hml.cmd.landtp:
    description: Grants access to /landtp command
    default: true
  hml.cmd.own:
    description: Grants access to /land own command
  hml.cmd.reload:
    description: Grants access to /land reload command
  hml.cmd.sell:
    description: Grants access to /land sell command
    default: true
  hml.cmd.teleport:
    description: Grants access to /land teleport command
    default: true
  hml.cmd.teleport.deleteothers:
    description: Allows player to delete other players warps
  hml.cmd.teleport.unlimited:
    description: Allows the purchase of unlimited teleports