name: HalfminerLand
version: ${project.version}
description: Halfminer.de land protection and management
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hml.HalfminerLand
depend: [HalfminerSystem, Essentials, WorldGuard]

commands:
  land:
    description: Base command
    aliases: [claim, zone, gebiet, l]
  landtp:
    description: Teleport to a land with a set teleport point
    aliases: [warpland, warpl]
  hml:
    description: Administrative commands
    aliases: [halfminerland, hmland]

permissions:
  hml.*:
    description: Access to all permissions
    default: op
    children:
      - hml.bypass.*
      - hml.cmd.buy
      - hml.cmd.buy.free
      - hml.cmd.buy.server
      - hml.cmd.fly
      - hml.cmd.friend
      - hml.cmd.hml
      - hml.cmd.info
      - hml.cmd.landtp
      - hml.cmd.list
      - hml.cmd.list.others
      - hml.cmd.list.teleport
      - hml.cmd.sell
      - hml.cmd.sell.force
      - hml.cmd.teleport
      - hml.cmd.teleport.deleteothers
      - hml.cmd.teleport.unlimited
      - hml.cmd.title
      - hml.cmd.title.formatting
      - hml.cmd.title.others
      - hml.ownsserverland
  hml.bypass.*:
    description: Access to all bypass permissions
    children:
      - hml.bypass.buydisabledworld
      - hml.bypass.friendlimit
      - hml.bypass.landtptimer
      - hml.bypass.minimumcoordinates
      - hml.bypass.permission
      - hml.bypass.teleportblacklist
      - hml.bypass.teleportlength
  hml.bypass.buydisabledworld:
    description: Bypasses disabled worlds during buy

  hml.bypass.friendlimit:
    description: Bypasses the friend limit per land
  hml.bypass.landtptimer:
    description: Bypasses teleport delay when teleporting via landtp to owned land
  hml.bypass.minimumcoordinates:
    description: Bypasses the minimum coordinates set to purchase a land
  hml.bypass.permission:
    description: Bypasses permission checks on lands, should be given to players who can build everywhere (WG bypass)
  hml.bypass.teleportblacklist:
    description: Bypasses teleport name blacklist set in config
  hml.bypass.teleportlength:
    description: Bypasses minimum/maximum length requirements set in config when buying a teleport
  hml.cmd.buy:
    description: Grants access to /land buy command
    default: true
  hml.cmd.buy.free:
    description: Grants access to unlimited free lands
  hml.cmd.buy.server:
    description: Grants access to /land buy server command
  hml.cmd.fly:
    description: Grants access to /land fly command
  hml.cmd.friend:
    description: Grants access to /land friend command
    default: true
  hml.cmd.hml:
    description: Grants access to /hml command
  hml.cmd.info:
    description: Grants access to /land info command
    default: true
  hml.cmd.landtp:
    description: Grants access to /landtp command
    default: true
  hml.cmd.list:
    description: Grants access to /land list command
    default: true
  hml.cmd.list.others:
    description: Access to list other player land
  hml.cmd.list.teleport:
    description: Teleport to land by clicking the land in list GUI
  hml.cmd.sell:
    description: Grants access to /land sell command
    default: true
  hml.cmd.sell.force:
    description: Grants access to /land sell force command
  hml.cmd.teleport:
    description: Grants access to /land teleport command
    default: true
  hml.cmd.teleport.deleteothers:
    description: Allows player to delete other players warps
  hml.cmd.teleport.unlimited:
    description: Allows the purchase of unlimited teleports
  hml.cmd.title:
    description: Allows setting land title messages that will be shown players actionbar
  hml.cmd.title.formatting:
    description: Allows using formatting codes in land title
  hml.cmd.title.others:
    description: Allows setting land titles for other players
  hml.ownsserverland:
    description: Players with this permission node are considered owners of land claimed for the server