name: HalfminerLand
version: ${project.version}
description: Halfminer.de land protection and management
author: Kakifrucht
website: https://halfminer.de
api-version: '1.14'

main: de.halfminer.hml.HalfminerLand
depend: [HalfminerSystem, Essentials, WorldGuard]

commands:
  land:
    description: Base command
    aliases: [claim, zone, gebiet]
    permission: hml.cmd
  landtp:
    description: Teleport to a land with a set teleport point
    aliases: [warpland, warpl]
    permission: hml.cmd.land
  hml:
    description: Administrative commands
    aliases: [halfminerland, hmland]
    permission: hml.cmd.hml

permissions:
  hml.*:
    description: Access to all permissions
    default: op
    children:
      - hml.bypass.*
      - hml.cmd.buy
      - hml.cmd.buy.free
      - hml.cmd.buy.server
      - hml.cmd.fly
      - hml.cmd.friend
      - hml.cmd.hml
      - hml.cmd.info
      - hml.cmd.land
      - hml.cmd.landtp
      - hml.cmd.list
      - hml.cmd.list.others
      - hml.cmd.list.teleport
      - hml.cmd.sell
      - hml.cmd.sell.force
      - hml.cmd.teleport
      - hml.cmd.teleport.deleteothers
      - hml.cmd.teleport.unlimited
      - hml.ownsserverland
  hml.bypass.*:
    description: Access to all bypass permissions
    children:
      - hml.bypass.breakplace
      - hml.bypass.buydisabledworld
      - hml.bypass.cmd
      - hml.bypass.friendlimit
      - hml.bypass.landtptimer
      - hml.bypass.minimumcoordinates
      - hml.bypass.teleportblacklist
      - hml.bypass.teleportlength
  hml.bypass.breakplace:
    description: Bypasses block break and placement protection
  hml.bypass.buydisabledworld:
    description: Bypasses disabled worlds during buy
  hml.bypass.cmd:
    description: Bypasses command block list in owned land
  hml.bypass.friendlimit:
    description: Bypasses the friend limit per land
  hml.bypass.landtptimer:
    description: Bypasses teleport delay when teleporting via landtp to owned land
  hml.bypass.minimumcoordinates:
    description: Bypasses the minimum coordinates set to purchase a land
  hml.bypass.teleportblacklist:
    description: Bypasses teleport name blacklist set in config
  hml.bypass.teleportlength:
    description: Bypasses minimum/maximum length requirements set in config when buying a teleport
  hml.cmd.buy:
    description: Grants access to /land buy command
    default: true
  hml.cmd.buy.free:
    description: Grants access to unlimited free lands
  hml.cmd.buy.server:
    description: Grants access to /land buy server command
  hml.cmd.fly:
    description: Grants access to /land fly command
  hml.cmd.friend:
    description: Grants access to /land friend command
    default: true
  hml.cmd.hml:
    description: Grants access to /hml command
  hml.cmd.info:
    description: Grants access to /land info command
    default: true
  hml.cmd.land:
    description: Grants access to /land base command
    default: true
  hml.cmd.landtp:
    description: Grants access to /landtp command
    default: true
  hml.cmd.list:
    description: Grants access to /land list command
    default: true
  hml.cmd.list.others:
    description: Access to list other player land
  hml.cmd.list.teleport:
    description: Teleport to land by clicking the land in list GUI
  hml.cmd.sell:
    description: Grants access to /land sell command
    default: true
  hml.cmd.sell.force:
    description: Grants access to /land sell force command
  hml.cmd.teleport:
    description: Grants access to /land teleport command
    default: true
  hml.cmd.teleport.deleteothers:
    description: Allows player to delete other players warps
  hml.cmd.teleport.unlimited:
    description: Allows the purchase of unlimited teleports
  hml.ownsserverland:
    description: Players with this permission node are considered owners of land claimed for the server