#HalfminerDuel Config
broadcastWin: true
noHungerLossInDuel: true
waitingForMatchRemind: 30
gameTime: 300
localization:
  prefix: '&7Duell &e>>&r '
  help: '&7Faire Duelle mit gleicher Ausruestung in Arenen.\n&e/duel <Spielername> - &7&oDuellanfrage schicken\n&e/duel match - &7&oDuellpartner finden\n&e/duel leave - &7&oWarteschlange verlassen\n&e/duel list - &7&oArenaliste anzeigen'
  pluginDisabled: '&cDas Plugin ist aktuell deaktiviert'
  showArenaList: '&aGruene Arenen&7 sind aktuell frei, &crote Arenen &7sind belegt: '
  addedToQueue: '&7Du bist nun in der Warteschlange, verwende &6/duel leave&7 zum verlassen'
  alreadyInQueue: '&cDu bist bereits in einer Warteschlange, verwende &6/duel leave&c zum verlassen'
  leftQueue: '&7Du hast die Warteschlange verlassen'
  notInQueue: '&cDu bist nicht in der Warteschlange'
  playerWaitingForMatch: '&e%PLAYER%&7 wartet auf einen Duellpartner. Gib &6/duel match&7 fuer ein faires Duell mit gleicher Ausruestung ein'
  removedFromQueueNotTheCause: '&cDein Duellpartner hat die Warteschlange verlassen, womit du auch entfernt wurdest'
  duelRequestSent: '&aDeine Herausforderung wurde an &e%PLAYER%&a geschickt, verwende &6/duel leave&a zum zurueckziehen'
  duelExempt: '&cDu kannst &e%PLAYER%&c keine Anfragen schicken'
  duelRequest: '&e%PLAYER%&7 hat dir eine Duell Herausforderung geschickt. Gib &6/duel %PLAYER% &7ein, um sie zu akzeptieren'
  duelRequestAlreadyOpen: '&cDu hast bereits eine offene Duell Herausforderung, verwende &6/duel leave&c zum zurueckziehen'
  duelRequestYourself: '&cDu kannst dir selber keine Anfrage schicken'
  duelNotOnline: '&cDer Spieler &e%PLAYER%&c ist nicht online oder existiert nicht'
  duelRequestCancel: '&aDeine Herausforderung wurde zurueckgezogen'
  duelRequestCancelled: '&e%PLAYER% &7hat seine Herausforderung zurueckgezogen'
  duelRequesteeNotAvailable: '&e%PLAYER%&c ist bereits in der Warteschlange oder im Spiel'
  duelRequestPending: '&cDu hast bereits eine offene Anfrage abgeschickt'
  duelRequestAccepted: '&aDu hast die Herausforderung akzeptiert'
  duelRequestWasAccepted: '&aDeine Anfrage wurde von &e%PLAYER%&a akzeptiert'
  duelAddedToQueue: '&bDu bist nun in der Warteschlange mit &e%PLAYER%&b, da alle Arenen in Verwendung sind'
  chooseArena: '&aGib im Chat die Nummer fuer die Arena ein, auf der du gegen &e%PLAYER%&a spielen willst: '
  chooseArenaRefreshed: '&bDie Auswahl wurde aktualisiert: '
  chooseArenaInvalid: '&cUngueltige Auswahl, bitte versuche es erneut'
  partnerChoosingArena: '&e%PLAYER%&7 waehlt nun eine Arena aus, das Duell startet gleich'
  gameStartingCountdown: '&7Das Duell in der Arena &e%ARENA%&7 gegen &c%PLAYER%&7 startet in 5 Sekunden'
  gameStarting: '&aDer Kampf beginnt!'
  inGame: '&cIm Kampf darfst du keine Kommandos verwenden'
  gameTimeRunningOut: '&cDas Duell wird in &e%TIME%&c Sekunden abgebrochen'
  gameWon: '&aDu hast das Duell gegen &e%PLAYER%&a gewonnen'
  gameLost: '&cDu hast das Duell gegen &e%PLAYER%&c verloren'
  gameTied: '&7Das Duell gegen &e%PLAYER%&7 ist unentschieden'
  gameBroadcast: '&a%WINNER% &7hat gegen &c%LOSER% &7in der Arena &e%ARENA% &7gewonnen'
  randomArena: 'Zufall'
  noPermission: '&cDu hast keine Rechte dies zu verwenden'
  adminHelp: '&7/hmd create <name> | /hmd remove <name> | /hmd spawnA <name> | /hmd spawnB <name> | /hmd setkit <arenaname> | /hmd reload'
  adminCreate: '&aDie Arena &e%ARENA%&a wurde erstellt. Verwende &6/hmd spawnA/spawnB %ARENA%&a um die Spawns zu setzen'
  adminCreateFailed: '&cDie Arena &e%ARENA%&c existiert bereits'
  adminRemove: '&aDie Arena &e%ARENA%&a wurde entfernt'
  adminArenaDoesntExist: '&cDie Arena &e%ARENA%&c existiert nicht'
  adminSetSpawn: '&aDer Spawn fuer die Arena &e%ARENA%&a wurde gesetzt'
  adminSetKit: '&aDas Kit fuer die Arena &e%ARENA%&a wurde gesetzt'
  adminSettingsReloaded: '&aDie Konfiguration wurde neugeladen'
#Arenas and Kits, to avoid issues don't edit them manually, use /hmd
arenas: []
kits: []