name: HalfminerDuel
version: 1.5.2
description: Halfminer.de Duel
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hmduel.HalfminerDuel

commands:
  duel:
    description: Duel base command
    usage: /duel <subcommand/playername>
    aliases: [1vs1,duell,pvp]
  hmd:
    description: Duel administrative command
    usage: /hmd <subcommand> [argument]
permissions:
  hmd.duel:
    default: true
    description: Default permission, allows usage of /duel
  hmd.duel.exempt:
    description: Exempt players cannot be duel requested
  hmd.admin:
    description: Administrative permission