name: HalfminerCore
version: ${project.version}
description: Halfminer.de Core Plugin
author: Kakifrucht
website: https://halfminer.de
api-version: '1.14'

main: de.halfminer.hmc.HalfminerCore
depend: [HalfminerSystem, Essentials]

commands:
  chat:
    description: Chat manipulation tools
    aliases: [c]
    permission: hmc.chat
  customtext:
    description: Show parsed customtext
    aliases: [hmctext, hmstext]
    permission: hmc.customttext
  disposal:
    description: Open portable disposal
    aliases: [bin]
    permission: hmc.disposal
  gems:
    description: Shows the users gem account
    aliases: [gem]
    permission: hmc.gems
  hmc:
    description: HalfminerCore base command and toolbox
    aliases: [halfminercore, hcore, hmcore]
    permission: hmc.moderator
  hmcapi:
    description: Command API
    aliases: [hmsapi]
    permission: hmc.admin
  hmstore:
    description: Data storage manipulation
    permission: hmc.admin
  home:
    description: Teleports the player to his home
    aliases: [h]
    permission: hmc.home
  lag:
    description: View the connection info
    aliases: [ping]
    permission: hmc.lag
  newtp:
    description: Teleports the player to a random location
    aliases: [tpnew, neutp, tpneu]
    permission: hmc.newtp
  pin:
    description: Generate temporary PIN code that identifes the player
    aliases: [code, key]
    permission: hmc.pin
  rank:
    description: Give custom ranks to players
    aliases: [rang]
    permission: hmc.rank
  repair:
    description: Repair the currently held item
    aliases: [fix]
    permission: hmc.repair
  sell:
    description: Earn money by selling farm supplies
    aliases: [verkauf, vk, clearcycle]
    permission: hmc.sell
  signedit:
    description: Edit the contents of a sign or copy it
    aliases: [se]
    permission: hmc.signedit
  spawn:
    description: Teleport to the spawn
    aliases: [sa, setspawn]
    permission: hmc.spawn
  stats:
    description: View the statistics of a player
    aliases: [st]
    permission: hmc.stats
  statstop:
    description: View the servers leaderboards
    aliases: [sttop, top]
    permission: hmc.statstop
  vote:
    description: Vote for the server
    permission: hmc.vote
permissions:
  hmc.*:
    description: Access to all permissions
    default: op
    children:
      hmc.antixray.notify: true
      hmc.admin: true
      hmc.chat: true
      hmc.chat.advanced: true
      hmc.customttext: true
      hmc.default: true
      hmc.disposal: true
      hmc.gems: true
      hmc.home: true
      hmc.lag: true
      hmc.lag.others: true
      hmc.lag.protected: true
      hmc.lag.notify: true
      hmc.moderator: true
      hmc.newtp: true
      hmc.pin: true
      hmc.rank: true
      hmc.sell: true
      hmc.sell.auto: true
      hmc.sell.clearcycle: true
      hmc.signedit: true
      hmc.spawn: true
      hmc.spawn.others: true
      hmc.spawn.set: true
      hmc.stats: true
      hmc.statstop: true
      hmc.vote: true
      hmc.bypass.*: true
      hmc.chat.*: true
      hmc.repair.*: true
  hmc.bypass.*:
    description: Access to all bypass permission
    default: op
    children:
      hmc.bypass.antixray: true
      hmc.bypass.combatlog: true
      hmc.bypass.commandfilter: true
      hmc.bypass.glitchcheck: true
      hmc.bypass.inventorysave: true
      hmc.bypass.hopperlimit: true
      hmc.bypass.nethercheck: true
      hmc.bypass.nokillfarming: true
      hmc.bypass.nokillfarmingrepeat: true
      hmc.bypass.pvp: true
      hmc.bypass.sellcyclesound: true
      hmc.bypass.skilllevel: true
      hmc.bypass.spawnerconvert: true
      hmc.bypass.statsrightclick: true
      hmc.bypass.teleportcheck: true
  hmc.chat.*:
    description: Access to all chat manager related permissions (not the command)
    default: op
    children:
      hmc.chat.allowcaps: true
      hmc.chat.allowcolor: true
      hmc.chat.allowformatcode: true
      hmc.chat.allowlinks: true
      hmc.chat.bypassglobalmute: true
      hmc.chat.spam: true
      hmc.chat.topformat: true
  hmc.repair.*:
    description: Full access to repair command
    default: op
    children:
      hmc.repair: true
      hmc.repair.all: true
      hmc.repair.nocooldown: true
      hmc.repair.stacks: true
  hmc.default:
    default: true
    description: Default permission
  hmc.gems:
    default: true
    description: Access to gems command
  hmc.stats:
    default: true
    description: Access to stats command
  hmc.statstop:
    default: true
    description: Access to statstop command
  hmc.sell:
    default: true
    description: Access to sell command
  hmc.vote:
    default: true
    description: Access to vote command
  hmc.admin:
    description: Access to administrative commands
  hmc.antixray.notify:
    description: Get notified on join if a player moved past the AntiXRay treshold
  hmc.bypass.antixray:
    description: Bypass antixray functionality
  hmc.bypass.combatlog:
    description: Bypass combat logging
  hmc.bypass.commandfilter:
    description: Bypass chat command filter
  hmc.bypass.glitchcheck:
    description: Bypass glitch movement check
  hmc.bypass.inventorysave:
    description: Bypass inventory dropping if keep inventory is set
  hmc.bypass.hopperlimit:
    description: Bypass hopper placement limit
  hmc.bypass.nethercheck:
    description: Bypass netherroof position check
  hmc.bypass.nokillfarming:
    description: Bypass killfarming check
  hmc.bypass.nokillfarmingrepeat:
    description: Bypass killfarming kill repeat check, used by other modules to determine if kill is grinded
  hmc.bypass.pvp:
    description: Bypass pvp modifications
  hmc.bypass.sellcyclesound:
    description: Bypass the sell cycle refresh notification sound
  hmc.bypass.skilllevel:
    description: Bypass setting and updating of skilllevel
    children:
    - hmc.bypass.skilllevel.update
  hmc.bypass.skilllevel.update:
    description: Bypass updating of skilllevel
  hmc.bypass.spawnerconvert:
    description: Allow converting mobspawners with mobeggs
  hmc.bypass.statsrightclick:
    description: Bypass stats on rightclick
  hmc.bypass.teleportcheck:
    description: Bypass glitch protection teleport check
  hmc.chat:
    description: Access to chat clearing command
  hmc.chat.advanced:
    description: Access to advanced chat manipulation
  hmc.chat.allowcaps:
    description: Stops filtering capitalised messages
  hmc.chat.allowcolor:
    description: Access to color codes in chat
  hmc.chat.allowformatcode:
    description: Access to format codes in chat
  hmc.chat.allowlinks:
    description: Allows posting links
  hmc.chat.spam:
    description: Bypass spam check protection
  hmc.chat.topformat:
    description: Gives user format with highest priority
  hmc.customttext:
    description: Access to customtext command
  hmc.disposal:
    description: Access to disposal command
  hmc.gems.admin:
    description: View and modify players gems accounts
  hmc.home:
    description: Access to home command
  hmc.lag:
    description: Access to lag command
  hmc.lag.others:
    description: View the latency of other players
  hmc.lag.protected:
    description: Players with this permission are exempt from ping lookup, if hmc.lag.others permission is granted
  hmc.lag.notify:
    description: Sends lag notifications to admin
  hmc.moderator:
    description: Access to moderative commands
  hmc.newtp:
    description: Access to newtp command
  hmc.pin:
    description: Access to pin command
  hmc.rank:
    description: Access to rank command
  hmc.repair:
    description: Access to repair command
  hmc.repair.all:
    description: Access to repair all command
  hmc.repair.nocooldown:
    description: No repair cooldown
  hmc.repair.stacks:
    description: Allows single stacks to be repaired
  hmc.sell.auto:
    description: Access to automatic selling
  hmc.sell.clearcycle:
    description: Access to /clearcycle command to force a new sell cycle
  hmc.signedit:
    description: Access to sign editing
  hmc.spawn:
    default: true
    description: Access to spawn command
  hmc.spawn.others:
    description: Teleport other players to spawn
  hmc.spawn.set:
    description: Access to spawn set command
