name: HalfminerWebAPI
version: ${project.version}
description: Halfminer.de HTTP API
author: Kakifrucht
website: https://halfminer.de

main: de.halfminer.hmwapi.HalfminerWebAPI
depend: [HalfminerSystem]

commands:
  hmwapi:
    description: Base command
    aliases: [hmw]

permissions:
  hmwapi.*:
    description: Access to all permissions
    default: op
    children:
      hmwapi.command: true
  hmwapi.command:
    description: Access to hmwapi command